application:
    port: 8000
database:
    host: "127.0.0.1"
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "newsletter"
email_client:
    base_url: "localhost"
    sender: "test@gmail.com"
    auth_token: "re_secret_token_1234567890"
    timeout_milliseconds: 10000
